# Generated by Django 3.2.6 on 2021-12-31 23:37

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tree_class', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='ConservationStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tree_status', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Family',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tree_family', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tree_order', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='SpecieStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('specie_status', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Tree',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scientific_name', models.CharField(help_text='Enter Generic, Specific and Author', max_length=100, validators=[django.core.validators.MinLengthValidator(3, 'Must be greater than 3')])),
                ('common_name', models.CharField(blank=True, max_length=50, null=True)),
                ('local_name', models.CharField(blank=True, max_length=50, null=True)),
                ('location_name', models.CharField(blank=True, max_length=50, null=True)),
                ('tree_description', models.TextField()),
                ('conservation_status', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='trees.conservationstatus')),
                ('specie_status', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='trees.speciestatus')),
                ('tree_family', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='trees.family')),
                ('tree_order', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='trees.order')),
            ],
        ),
    ]
