# Generated by Django 3.2.6 on 2022-01-01 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trees', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tree',
            name='location_description',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='tree',
            name='location_name',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
