# Generated by Django 4.1.4 on 2023-01-11 23:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("trees", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="class",
            options={"verbose_name_plural": "class"},
        ),
        migrations.AlterModelOptions(
            name="family",
            options={"verbose_name_plural": "families"},
        ),
    ]
