# Generated by Django 4.1.4 on 2023-01-24 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trees", "0002_alter_class_options_alter_family_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="tree",
            name="leaf_image",
            field=models.ImageField(blank=True, null=True, upload_to="tree_leaf"),
        ),
    ]
