# Generated by Django 3.2.6 on 2022-01-01 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trees', '0003_auto_20220101_1215'),
    ]

    operations = [
        migrations.AddField(
            model_name='tree',
            name='authority',
            field=models.CharField(max_length=80, null=True),
        ),
    ]
