# Generated by Django 3.2.6 on 2022-01-01 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trees', '0004_tree_authority'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tree',
            name='authority',
            field=models.CharField(default='------', max_length=80),
        ),
    ]
