# Generated by Django 3.2.6 on 2022-01-01 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trees', '0005_alter_tree_authority'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tree',
            name='common_name',
            field=models.CharField(default='------', max_length=50),
        ),
        migrations.AlterField(
            model_name='tree',
            name='local_name',
            field=models.CharField(default='------', max_length=50),
        ),
    ]
