# Generated by Django 3.2.6 on 2022-01-02 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trees', '0006_auto_20220101_1808'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tree',
            options={'ordering': ['scientific_name']},
        ),
        migrations.AddField(
            model_name='tree',
            name='pharmacological_details',
            field=models.TextField(default='------'),
        ),
    ]
