# Generated by Django 3.2.6 on 2022-01-02 19:16

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('trees', '0008_alter_tree_pharmacological_details'),
    ]

    operations = [
        migrations.AddField(
            model_name='tree',
            name='last_updated',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
