# Generated by Django 3.2.6 on 2022-01-02 22:30

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('trees', '0009_tree_last_updated'),
    ]

    operations = [
        migrations.AddField(
            model_name='tree',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='tree',
            name='last_updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
