# Generated by Django 4.0.1 on 2022-01-16 07:29

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trees', '0012_tree_genus_specie'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tree',
            name='genus_specie',
            field=models.CharField(default='', help_text='Enter Generic and Specific name', max_length=100, validators=[django.core.validators.MinLengthValidator(3, 'Must be greater than 3')]),
        ),
    ]
