# Generated by Django 4.0.1 on 2022-01-27 22:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trees', '0014_tree_reference'),
    ]

    operations = [
        migrations.CreateModel(
            name='Authority',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tree_authority', models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='tree',
            name='authority',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='trees.authority'),
        ),
    ]
