# Generated by Django 4.0.1 on 2022-01-27 22:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trees', '0016_rename_authority_tree_tree_authority_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tree',
            old_name='tree_authority',
            new_name='authority',
        ),
    ]
