# Generated by Django 4.1.4 on 2021-12-19 10:21

import django.core.validators
from django.db import migrations, models
import django_resized.forms


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("trees", "__first__"),
    ]

    operations = [
        migrations.CreateModel(
            name="SpecialPlace",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tree_count",
                    models.IntegerField(
                        default=0,
                        validators=[django.core.validators.MinValueValidator(1)],
                    ),
                ),
                (
                    "tree_picture",
                    django_resized.forms.ResizedImageField(
                        crop=None,
                        force_format=None,
                        keep_meta=True,
                        quality=-1,
                        scale=None,
                        size=[400, None],
                        upload_to="images/specials/%Y/%m/%d/",
                    ),
                ),
                (
                    "tree_picture2",
                    django_resized.forms.ResizedImageField(
                        blank=True,
                        crop=None,
                        force_format=None,
                        keep_meta=True,
                        null=True,
                        quality=-1,
                        scale=None,
                        size=[500, None],
                        upload_to="images/specials/%Y/%m/%d/",
                    ),
                ),
                (
                    "tree_picture3",
                    django_resized.forms.ResizedImageField(
                        blank=True,
                        crop=None,
                        force_format=None,
                        keep_meta=True,
                        null=True,
                        quality=-1,
                        scale=None,
                        size=[500, None],
                        upload_to="images/specials/%Y/%m/%d/",
                    ),
                ),
                (
                    "special_place_name",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("location_name", models.CharField(max_length=80)),
                ("location_description", models.TextField()),
                ("coordinates", models.CharField(blank=True, max_length=30, null=True)),
                ("latitude", models.CharField(blank=True, max_length=30, null=True)),
                ("longitude", models.CharField(blank=True, max_length=30, null=True)),
                ("time_now", models.DateTimeField(auto_now=True)),
                ("uploader", models.CharField(blank=True, max_length=50, null=True)),
                ("tree_specie_found", models.ManyToManyField(to="trees.tree")),
            ],
        ),
    ]
