# Generated by Django 4.0.1 on 2022-02-06 10:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Special',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tree_count', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(1)])),
                ('tree_picture', models.ImageField(upload_to='')),
                ('tree_picture2', models.ImageField(blank=True, null=True, upload_to='')),
                ('tree_picture3', models.ImageField(blank=True, null=True, upload_to='')),
                ('location_name', models.CharField(max_length=80)),
                ('location_description', models.TextField()),
                ('coordinates', models.CharField(blank=True, max_length=30, null=True)),
                ('latitude', models.CharField(blank=True, max_length=30, null=True)),
                ('longitude', models.CharField(blank=True, max_length=30, null=True)),
                ('time_now', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
