# Generated by Django 4.0.1 on 2022-02-06 10:21

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trees', '0019_remove_tree_tree_authority_alter_tree_authority'),
        ('specialplaces', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpecialPlace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tree_count', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(1)])),
                ('tree_picture', models.ImageField(upload_to='')),
                ('tree_picture2', models.ImageField(blank=True, null=True, upload_to='')),
                ('tree_picture3', models.ImageField(blank=True, null=True, upload_to='')),
                ('location_name', models.CharField(max_length=80)),
                ('location_description', models.TextField()),
                ('coordinates', models.CharField(blank=True, max_length=30, null=True)),
                ('latitude', models.CharField(blank=True, max_length=30, null=True)),
                ('longitude', models.CharField(blank=True, max_length=30, null=True)),
                ('time_now', models.DateTimeField(auto_now=True)),
                ('tree_name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='trees.tree')),
            ],
        ),
        migrations.DeleteModel(
            name='Special',
        ),
    ]
