# Generated by Django 4.1.4 on 2023-01-20 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("specialplaces", "0002_alter_specialplace_tree_picture_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="specialplace",
            name="coordinates",
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name="specialplace",
            name="latitude",
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name="specialplace",
            name="longitude",
            field=models.CharField(max_length=30),
        ),
    ]
