# Generated by Django 4.0.1 on 2022-02-10 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trees', '0019_remove_tree_tree_authority_alter_tree_authority'),
        ('specialplaces', '0002_specialplace_delete_special'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='specialplace',
            name='tree_name',
        ),
        migrations.AddField(
            model_name='specialplace',
            name='tree_specie_name',
            field=models.ManyToManyField(to='trees.Tree'),
        ),
    ]
