# Generated by Django 4.0.1 on 2022-02-10 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trees', '0019_remove_tree_tree_authority_alter_tree_authority'),
        ('specialplaces', '0003_remove_specialplace_tree_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='specialplace',
            name='tree_specie_name',
        ),
        migrations.AddField(
            model_name='specialplace',
            name='special_place_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='specialplace',
            name='tree_specie_found',
            field=models.ManyToManyField(to='trees.Tree'),
        ),
    ]
