# Generated by Django 4.0.1 on 2022-03-30 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('specialplaces', '0007_alter_specialplace_tree_picture_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='specialplace',
            name='uploader',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
