# Generated by Django 4.0.4 on 2022-12-11 07:06

from django.db import migrations
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('specialplaces', '0009_alter_specialplace_tree_picture_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='specialplace',
            name='tree_picture',
            field=django_resized.forms.ResizedImageField(crop=None, force_format=None, keep_meta=True, quality=-1, scale=None, size=[400, None], upload_to='images/specials/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='specialplace',
            name='tree_picture2',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format=None, keep_meta=True, null=True, quality=-1, scale=None, size=[500, None], upload_to='images/specials/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='specialplace',
            name='tree_picture3',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format=None, keep_meta=True, null=True, quality=-1, scale=None, size=[500, None], upload_to='images/specials/%Y/%m/%d/'),
        ),
    ]
