# Generated by Django 4.1.4 on 2021-12-19 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Search",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=25)),
                ("search_by", models.CharField(max_length=25)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
    ]
