# Generated by Django 3.2.6 on 2022-01-09 07:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_steal'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Steal',
        ),
    ]
