# Generated by Django 4.0.1 on 2022-02-12 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_delete_steal'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contributors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture', models.ImageField(upload_to='images/%Y/%m/%d/')),
                ('name', models.CharField(max_length=50)),
                ('profile', models.TextField()),
                ('mail', models.EmailField(default='dharmzeey@gmail.com', max_length=254)),
                ('tel', models.IntegerField(default=234)),
                ('website', models.URLField(blank=True, null=True)),
                ('git_link', models.URLField(blank=True, null=True)),
                ('tw_link', models.URLField(blank=True, null=True)),
                ('ig_link', models.URLField(blank=True, null=True)),
                ('fb_link', models.URLField(blank=True, null=True)),
            ],
        ),
    ]
