# Generated by Django 4.0.1 on 2022-02-12 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_remove_contributors_mail'),
    ]

    operations = [
        migrations.AddField(
            model_name='contributors',
            name='mail',
            field=models.EmailField(default='dharmzeey@gmail.com', max_length=254),
        ),
    ]
