# Generated by Django 4.0.1 on 2022-02-15 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_contributors_mail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contributors',
            name='picture',
            field=models.ImageField(upload_to='contributors/%Y/%m/%d/'),
        ),
    ]
