# Generated by Django 4.0.1 on 2022-02-27 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_alter_contributors_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contributors',
            name='mail',
            field=models.EmailField(max_length=254),
        ),
    ]
