# Generated by Django 4.0.1 on 2022-03-19 08:08

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_alter_contributors_mail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contributors',
            name='tel',
            field=models.CharField(max_length=17, validators=[django.core.validators.RegexValidator(message='Number Must be in +234 format', regex='^\\+?1?\\d{9,15}$')]),
        ),
    ]
