# Generated by Django 4.0.4 on 2022-08-27 14:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_delete_contributor'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='search',
            options={'ordering': ['name']},
        ),
    ]
