# Generated by Django 3.2.6 on 2022-01-02 10:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('trees', '0006_auto_20220101_1808'),
    ]

    operations = [
        migrations.CreateModel(
            name='Upload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tree_picture', models.ImageField(upload_to='')),
                ('location_name', models.CharField(max_length=80)),
                ('location_description', models.TextField()),
                ('tree_name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='trees.tree')),
            ],
        ),
    ]
