# Generated by Django 3.2.6 on 2022-01-02 22:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='upload',
            name='location_description',
        ),
    ]
