# Generated by Django 4.1.4 on 2023-01-13 22:55

from django.db import migrations
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ("upload", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="upload",
            name="tree_picture",
            field=django_resized.forms.ResizedImageField(
                crop=None,
                force_format=None,
                keep_meta=True,
                quality=-1,
                scale=None,
                size=[800, None],
                upload_to="images/uploads/%Y/%m/%d/",
            ),
        ),
    ]
