# Generated by Django 4.1.4 on 2023-01-14 00:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("upload", "0002_alter_upload_tree_picture"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="upload",
            name="uploader",
        ),
        migrations.AddField(
            model_name="upload",
            name="requested_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="requested_by",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="upload",
            name="uploaded_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="uploaded_by",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
