# Generated by Django 3.2.6 on 2022-01-02 22:07

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0002_remove_upload_location_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='upload',
            name='location_description',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
