# Generated by Django 3.2.6 on 2022-01-02 22:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0003_upload_location_description'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='upload',
            options={'ordering': ['tree_name']},
        ),
    ]
