# Generated by Django 4.1.4 on 2023-01-20 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("upload", "0003_remove_upload_uploader_upload_requested_by_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="upload",
            name="coordinates",
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name="upload",
            name="latitude",
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name="upload",
            name="longitude",
            field=models.CharField(max_length=30),
        ),
    ]
