# Generated by Django 3.2.6 on 2022-01-05 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0016_alter_upload_tree_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='upload',
            name='tree_picture',
            field=models.ImageField(height_field='300', upload_to='wss', width_field='300'),
        ),
    ]
