# Generated by Django 3.2.6 on 2022-01-09 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0020_alter_upload_tree_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='upload',
            name='coordinates',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
