# Generated by Django 3.2.6 on 2022-01-09 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0021_upload_coordinates'),
    ]

    operations = [
        migrations.AlterField(
            model_name='upload',
            name='coordinates',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
