# Generated by Django 3.2.6 on 2022-01-09 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0022_alter_upload_coordinates'),
    ]

    operations = [
        migrations.AlterField(
            model_name='upload',
            name='coordinates',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
