# Generated by Django 4.0.1 on 2022-01-15 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0024_auto_20220109_1850'),
    ]

    operations = [
        migrations.AddField(
            model_name='upload',
            name='tree_picture2',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='upload',
            name='tree_picture3',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
