# Generated by Django 4.0.1 on 2022-01-15 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0026_upload_tree_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='upload',
            name='tree_count',
            field=models.IntegerField(default=0),
        ),
    ]
