# Generated by Django 4.0.1 on 2022-01-15 12:19

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0027_alter_upload_tree_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='upload',
            name='tree_count',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
