# Generated by Django 4.0.1 on 2022-01-16 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0030_alter_upload_tree_count'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimeUpdate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_now', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
