# Generated by Django 4.0.1 on 2022-01-16 11:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0032_rename_time_now_timeupdate_time_then_timeupdate_name_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TimeUpdate',
        ),
    ]
