# Generated by Django 4.0.1 on 2022-03-07 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0037_treestatus_upload_health_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='upload',
            name='uploader',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
