# Generated by Django 4.0.1 on 2022-05-07 20:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0038_upload_uploader'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='upload',
            options={'ordering': ['location_name']},
        ),
    ]
