# Generated by Django 4.1.4 on 2022-12-13 21:59

from django.db import migrations, models
import django_resized.forms
import uuid


class Migration(migrations.Migration):

    dependencies = [
        (
            "upload",
            "0041_alter_upload_tree_picture_alter_upload_tree_picture2_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="upload",
            name="temp_id",
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
        migrations.AlterField(
            model_name="upload",
            name="tree_picture",
            field=django_resized.forms.ResizedImageField(
                crop=None,
                force_format=None,
                keep_meta=True,
                quality=-1,
                scale=None,
                size=[400, None],
                upload_to="images/uploads/%Y/%m/%d/",
            ),
        ),
    ]
