# Generated by Django 4.1.4 on 2022-12-13 22:25

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("upload", "0042_upload_temp_id_alter_upload_tree_picture"),
    ]

    operations = [
        migrations.AlterField(
            model_name="upload",
            name="temp_id",
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
