# Generated by Django 4.1.4 on 2022-12-13 22:25

from django.db import migrations
import uuid


def gen_uuid(apps, schema_editor):
    MyModel = apps.get_model('upload', 'Upload')
    for row in MyModel.objects.all():
        row.temp_id = uuid.uuid4()
        row.save(update_fields=['temp_id'])


class Migration(migrations.Migration):

    dependencies = [
        ("upload", "0043_alter_upload_temp_id"),
    ]

    operations = [
        migrations.RunPython(gen_uuid, reverse_code=migrations.RunPython.noop),
    ]
