# Generated by Django 4.0.1 on 2022-05-07 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authority', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myusercreationmodel',
            name='picture',
            field=models.ImageField(default='avatar.svg', null=True, upload_to='contributors/%Y/%m/%d/'),
        ),
    ]
