# Generated by Django 4.0.1 on 2022-05-07 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authority', '0002_alter_myusercreationmodel_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myusercreationmodel',
            name='picture',
            field=models.ImageField(default="{% static 'icon/avatar.svg' %}", null=True, upload_to='contributors/%Y/%m/%d/'),
        ),
    ]
