# Generated by Django 4.1.4 on 2021-12-19 10:21

from django.db import migrations, models
import django_resized.forms
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="RequestTree",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("location_name", models.CharField(max_length=100)),
                ("location_description", models.TextField()),
                (
                    "tree_picture",
                    django_resized.forms.ResizedImageField(
                        crop=None,
                        force_format=None,
                        keep_meta=True,
                        quality=-1,
                        scale=None,
                        size=[500, None],
                        upload_to="images/request/%Y/%m/%d",
                    ),
                ),
                (
                    "tree_picture2",
                    django_resized.forms.ResizedImageField(
                        blank=True,
                        crop=None,
                        force_format=None,
                        keep_meta=True,
                        null=True,
                        quality=-1,
                        scale=None,
                        size=[500, None],
                        upload_to="images/request/%Y/%m/%d/",
                    ),
                ),
                ("coordinates", models.CharField(blank=True, max_length=30, null=True)),
                ("latitude", models.CharField(blank=True, max_length=30, null=True)),
                ("longitude", models.CharField(blank=True, max_length=30, null=True)),
            ],
        ),
    ]
