# Generated by Django 4.1.4 on 2023-01-20 02:34

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("treerequest", "0002_requesttree_requester_alter_requesttree_tree_picture"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="requesttree",
            options={"ordering": ["requested"]},
        ),
        migrations.AddField(
            model_name="requesttree",
            name="requested",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="requesttree",
            name="coordinates",
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name="requesttree",
            name="latitude",
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name="requesttree",
            name="longitude",
            field=models.CharField(max_length=30),
        ),
    ]
