# Generated by Django 4.0.1 on 2022-02-27 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('treerequest', '0003_alter_requesttree_tree_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='requesttree',
            name='tree_picture2',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/%Y/%m/%d/'),
        ),
    ]
