# Generated by Django 4.0.1 on 2022-02-27 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('treerequest', '0004_requesttree_tree_picture2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requesttree',
            name='tree_picture2',
            field=models.ImageField(blank=True, null=True, upload_to='request/%Y/%m/%d/'),
        ),
    ]
